source "https://rubygems.org"

gem "jekyll", "~> 4.1"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-mentions", "~> 1.6.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-seo-tag", "~> 2.6.1"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-commonmark", "~> 1.3.1"
gem "jekyll-include-cache", "~> 0.2"
gem "jemoji", "~> 0.12"
gem "jekyll-remote-theme", "~> 0.3"
gem "webrick", ">= 1.8.2"
gem "google-protobuf", ">= 3.25.5"
gem "rexml", ">= 3.3.6"
gem "nokogiri", ">= 1.16.5"
gem "commonmarker", ">= 0.23.10"
gem "nokogiri", ">= 1.16.5"
gem "activesupport", ">= 7.0.7.1"
